import Head from 'next/head'
import {GraphQLClient, gql} from "graphql-request"
import BlogCard from '@/components/BlogCard'
import Navbar from '@/components/Navbar'

const graphcms = new GraphQLClient("https://api-ap-southeast-2.hygraph.com/v2/clcx3t4zy218k01ujf0ja33lo/master")

const QUERY = gql`
query Posts {
  posts {
    createdAt
    updatedAt
    id
    slug
    title
    tags
    content {
      html
      text
    }
    coverPhoto {
      url
    }
  }
}
`

export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts: posts.reverse(),
    },
  }
}

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Rablog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=devicewidth, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main >
 
        <Navbar/>

        <section className="mt-40 w-3/4 m-auto pt-10">
          { posts.length 
            ? 
              posts.map((post) => <BlogCard key={post.id} tags={post.tags} title={post.title} content={post.content} createdAt={post.createdAt} updatedAt={post.updatedAt} slug={post.slug} coverPhoto={post.coverPhoto}/>)
            : 
              <div className="text-center">
                <p className="text-3xl text-gray-400 font-bold">Looks like there are no posts :(</p>
              </div>
          }
        </section>

      </main>
    </>
  )
}
